name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore dependencies
        working-directory: ./src/DigmaSSEServer
        run: dotnet restore
        
      - name: Build
        working-directory: ./src/DigmaSSEServer
        run: dotnet build --no-restore
        
      - name: Test
        working-directory: ./src/DigmaSSEServer
        run: dotnet test --no-build --verbosity normal 